### ISSUE TITLE
@BsonDiscriminator not fully working

### ISSUE THREAD

**Issue by mnembrini** [micronaut-projects/micronaut-mongodb#10]
Although it's not documented in Micronaut Mongo, a feature of the mongo driver is that you can map elements of a collection to specific subclasses based on a field called the discriminator, see this example in C# https://stackoverflow.com/questions/18465529/mongodb-mapping-an-interface-to-an-implementation
Or the docs for this feature in the C# driver https://mongodb.github.io/mongo-csharp-driver/2.8/reference/bson/mapping/polymorphism/

My issue is that I could not find a mechanism to register classes with the automatic Pojo codec, so the code is flaky. For some reason at insert time the inserted class is registered automatically, so my current workaround for this is to insert and delete one item of every type I'm dealing with. The mapping of discriminator key to Class is in org.bson.codecs.pojo.DiscriminatorLookup

See this example: https://github.com/mnembrini/micronaut-bug-bson-discriminator

In there there is an Animal base class with subclasses Dog and Cat, and a single mongoDB collection "animal". The expectation is that we get the right class when reading based on the discriminator key "type"

In AnimalRepositoryTest, if you run the whole test class, everything passes, because there is an insert of both Dog and Cat classes in the DB.
If after that you run only the test readCatWithoutInsertingFirst(), it will fail with the following exception

```
An exception occurred when decoding using the AutomaticPojoCodec.
Decoding into a 'Animal' failed with the following exception:

Failed to decode 'Animal'. Decoding errored with: A class could not be found for the discriminator: 'some_cat_type'.

A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.
org.bson.codecs.configuration.CodecConfigurationException: An exception occurred when decoding using the AutomaticPojoCodec.
Decoding into a 'Animal' failed with the following exception:

Failed to decode 'Animal'. Decoding errored with: A class could not be found for the discriminator: 'some_cat_type'.

A custom Codec or PojoCodec may need to be explicitly configured and registered to handle this type.
	at org.bson.codecs.pojo.AutomaticPojoCodec.decode(AutomaticPojoCodec.java:40)
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:409)
	at com.mongodb.internal.connection.InternalStreamConnection.access$900(InternalStreamConnection.java:74)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:394)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:372)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:667)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:562)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:74)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:624)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:609)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.bson.codecs.configuration.CodecConfigurationException: Failed to decode 'Animal'. Decoding errored with: A class could not be found for the discriminator: 'some_cat_type'.
	at org.bson.codecs.pojo.PojoCodecImpl.getCodecFromDocument(PojoCodecImpl.java:354)
	at org.bson.codecs.pojo.PojoCodecImpl.decode(PojoCodecImpl.java:124)
	at org.bson.codecs.pojo.AutomaticPojoCodec.decode(AutomaticPojoCodec.java:37)
	... 41 more
Caused by: org.bson.codecs.configuration.CodecConfigurationException: A class could not be found for the discriminator: 'some_cat_type'.
	at org.bson.codecs.pojo.DiscriminatorLookup.lookup(DiscriminatorLookup.java:51)
	at org.bson.codecs.pojo.PojoCodecImpl.getCodecFromDocument(PojoCodecImpl.java:352)
	... 43 more
```

The test readDogWithoutInsertingFirst instead works, because the discriminator key for Dog is the name of the class. This is also another possible workaround, but I don't think it's robust

**Comment by rozza** [comment]
The issue is the automatic PojoCodec is lazy, so custom discriminators that don't use the full classpath risk not being seen by the PojoCodec and therefore can't be handled.

As the error message says, they need to be explicitly registered to handle these types.

**Comment by mnembrini** [comment]
How would you do the registration though? I could not find documentation or clearly named functions in the few obvious classes I looked into

**Comment by rozza** [comment]
Through the [PojoCodecProvider.Builder#register](http://mongodb.github.io/mongo-java-driver/3.12/javadoc/org/bson/codecs/pojo/PojoCodecProvider.Builder.html) method.  There you explicitly register what classes to support.  By declaring the class, the discriminator is registered explicitly.

**Comment by mnembrini** [comment]
Thanks for helping. I'm working on this only when I have some extra time since it's low priority now that we have a work around. 

I saw that method, but how I do I get an instance of the builder? 
In io.micronaut.configuration.mongo.reactive.AbstractReactiveMongoConfiguration#buildSettings
the PojoCodecProvider builder is created and then configured, but it's not really exposed to the client application.

**Comment by graemerocher** [comment]
Currently we set `automatic` to `true`. @rozza Is that not enough? 

http://mongodb.github.io/mongo-java-driver/3.12/javadoc/org/bson/codecs/pojo/PojoCodecProvider.Builder.html#automatic(boolean)

**Comment by graemerocher** [comment]
Oh i see your previous answer. Ok well we will take it as an improvement request to register entities or allow customization of the builder
