### ISSUE TITLE
Codec error when using the blocking driver

### ISSUE THREAD

**Issue by mohitmutha** [micronaut-projects/micronaut-mongodb#12]
I am trying to setup a microservice with the blocking mongodb driver. I followed the steps mentioned in the readme. However I faced the following issues 

1. If I remove the dependency `io.micronaut.configuration:micronaut-mongo-reactive` I get a runtime error 

```
No bean of type [com.mongodb.client.MongoClient] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1903)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1021)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1379)
	... 44 common frames omitted
```
So I retained the dependency and the error goes away. 

2. When using the MongoClient for inserting POJO's I get a error that `Can't find a codec for class XXXX`. Below is the code snippet

```
  @Post
  public void createPerson(@Body Person person){
    getCollection().insertOne(person);
  }

  private MongoCollection<Person> getCollection(){
    return mongoClient.getDatabase("persons").getCollection("personC", Person.class);
  }
```
So I had to write a mongoClient bean as below 
```
package com.mm;

import com.mongodb.client.MongoClient;
import com.mongodb.MongoClientSettings;
import com.mongodb.client.MongoClients;
import io.micronaut.context.annotation.Bean;
import io.micronaut.context.annotation.Factory;
import io.micronaut.context.annotation.Primary;
import io.micronaut.context.annotation.Requires;
import org.bson.codecs.configuration.CodecRegistry;
import org.bson.codecs.pojo.PojoCodecProvider;

import javax.inject.Singleton;

import static org.bson.codecs.configuration.CodecRegistries.fromProviders;
import static org.bson.codecs.configuration.CodecRegistries.fromRegistries;

@Requires(classes = MongoClient.class)
@Requires(beans = DefaultMongoConfiguration.class)
@Factory
public class MongoClientFactory {

  /**
   * Factory method to return a client.
   * @param configuration configuration pulled in
   * @return mongoClient
   */
  @Bean(preDestroy = "close")
  @Primary
  @Singleton
  MongoClient mongoClient(DefaultMongoConfiguration configuration) {
    CodecRegistry pojoCodecRegistry = fromRegistries(MongoClientSettings.getDefaultCodecRegistry(),
            fromProviders(PojoCodecProvider.builder().automatic(true).build()));
    MongoClientSettings settings = MongoClientSettings.builder()
            .codecRegistry(pojoCodecRegistry)
            .build();
    MongoClient mongoClient = MongoClients.create(settings);
    return mongoClient;
  }
}
```

With this it worked. 

My question is whether this is the right way to do this or there is a better way?

**Comment by graemerocher** [comment]
currently yes. We need to update the blocking implementation to allow customization of the codecs, but when we originally wrote it that wasn't possible
