### ISSUE TITLE
Mongo Reactive with GraalVM throws: CodecConfigurationException: Can't find a codec for class [Class]

### ISSUE THREAD

**Issue by cantte** [micronaut-projects/micronaut-mongodb#307]
### Expected Behavior

That I did not throw the exception and that it finds the codec

### Actual Behaviour

throws: CodecConfigurationException: Can't find a codec for class [Class]

### Steps To Reproduce

1. Go to https://guides.micronaut.io/latest/micronaut-mongodb-asynchronous-gradle-kotlin.html and dowload source code
2. Create a docker container with docker (Optional, for local test); you can set the mongodb.uri parameter with your database connection string
3. Generate a native file with GraalVM
4. Run native binary
5. Run `curl -i localhost:8080/fruits` following the example of the guide, you can also execute the POST, the error appears in both methods
6. You maybe receive a response like `{"message":"Internal Server Error","_links":{"self":{"href":"/fruits","templated":false}},"_embedded":{"errors":[{"message":"Internal Server Error: Can't find a codec for class example.micronaut.Fruit."}]}}`

### Environment Information

- Operating System: Ubuntu 22.04 LTS
- JDK Version: 11
- GraalVM: 22.0.0.2.r11-grl (recommended in the tutorial for java 11)

### Example Application

https://guides.micronaut.io/latest/micronaut-mongodb-asynchronous-gradle-kotlin.html

### Version

3.4.1

**Comment by cantte** [comment]
additional information, when I run the compiled app normally (`using ./gradlew run`)
I notice that the following message appears in the log records `INFO e.micronaut.MongoDbFruitRepository - Client codecs: org.bson.codecs.pojo.AutomaticPojoCodec@2884d0e4` after calling an http method.

Instead, with the application compiled with GraalVM the message not apperars and I get the error for which I opened this issue

```
Unexpected error occurred: Can't find a codec for class example.micronaut.Fruit.
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class example.micronaut.Fruit.
        at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
        at java.util.Optional.orElseThrow(Optional.java:408)
        at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
        at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:64)
        at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:39)
        at example.micronaut.MongoDbFruitRepository.save(MongoDbFruitRepository.java:34)
        at example.micronaut.$MongoDbFruitRepository$Definition$Intercepted.$$access$$save(Unknown Source)
        at example.micronaut.$MongoDbFruitRepository$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
```

I tried the example in Java and still get the same error.

**Comment by graemerocher** [comment]
You need to add `@ReflectiveAccess` to the fruit type. 

Alternatively you can instead use Micronaut Data MongoDB which doesn't require reflection to deserialise and serialise https://guides.micronaut.io/latest/micronaut-data-mongodb-asynchronous.html

Having said that this should be covered by the guide
