### ISSUE TITLE
Can't find a codec for CodecCacheKey

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-mongodb#458]
### Expected Behavior

Document class

```java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor(staticName = "of")
public class Customer {
    private ObjectId id;
    private String name;
    private int age;
    private Address address;

    public static Customer of(String name, int age, Address address) {
        return Customer.of(null, name, age, address);
    }
}
```

CustomerRepository:

```java
@Singleton
@RequiredArgsConstructor
@Slf4j
public class CustomerRepository {
    private final MongoClient mongoClient;
    private final DefaultMongoConfiguration mongoConfiguration;

    public Flux<Customer> findAll() {
        return Flux.from(customersCollection().find());
    }

    public Mono<Customer> findById(ObjectId id) {
        return Mono.from(customersCollection().find(Filters.eq(id)));
    }

    public Mono<ObjectId> insertOne(Customer data) {
        return Mono.from(customersCollection().insertOne(data, new InsertOneOptions().bypassDocumentValidation(false)))
                .mapNotNull(result -> result.getInsertedId().asObjectId().getValue());
    }

    public Mono<Map<Integer, BsonValue>> insertMany(List<Customer> data) {
        return Mono.from(customersCollection().insertMany(data, new InsertManyOptions().bypassDocumentValidation(false).ordered(true)))
                .map(InsertManyResult::getInsertedIds);
    }

    public Mono<Long> deleteById(ObjectId id) {
        return Mono.from(customersCollection().deleteOne(Filters.eq(id), new DeleteOptions()))
                .map(DeleteResult::getDeletedCount);
    }

    public void init() {
        var people = List.of(
                Customer.of("Charles Babbage", 45, Address.of("5 Devonshire Street", "London", "W11")),
                Customer.of("Alan Turing", 28, Address.of("Bletchley Hall", "Bletchley Park", "MK12")),
                Customer.of("Timothy Berners-Lee", 61, Address.of("Colehill", "Wimborne", null))
        );
        Mono.from(customersCollection().drop())
                .then()
                .thenMany(this.insertMany(people))
                .subscribe(
                        result -> result.forEach((key, value) -> log.debug("saved key: {}, value: {}", key, value)),
                        error -> log.debug("initialization failed: {}", error),
                        () -> log.debug("done")
                );
    }

    public Mono<Long> deleteAll() {
        return Mono.from(customersCollection().deleteMany(Filters.empty(), new DeleteOptions()))
                .map(DeleteResult::getDeletedCount);
    }

    private MongoCollection<Customer> customersCollection() {
        return mongoClient
                .getDatabase("userdb")
                .getCollection("customers", Customer.class);
    }


}
```

The testing codes failed now:

https://github.com/hantsy/micronaut-sandbox/blob/master/mongodb-album-service/src/test/groovy/com/example/CustomerRepositorySpec.groovy#L55-L68

### Actual Behaviour

```bash 
 CustomerRepositorySpec > test findAll FAILED
    org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for CodecCacheKey{clazz=class com.example.customers.Customer, types=null}.
        at app//org.bson.internal.ProvidersCodecRegistry.lambda$get$0(ProvidersCodecRegistry.java:87)
        at java.base@17.0.7/java.util.Optional.orElseGet(Optional.java:364)
        at app//org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:80)
        at app//org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:50)
        at app//com.mongodb.internal.operation.Operations.getCodec(Operations.java:709)
        at app//com.mongodb.internal.operation.Operations.insertMany(Operations.java:443)
        at app//com.mongodb.internal.operation.AsyncOperations.insertMany(AsyncOperations.java:236)
        at app//com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.lambda$insertMany$7(MongoOperationPublisher.java:269)
        at app//com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.createWriteOperationMono(MongoOperationPublisher.java:423)
```

### Environment Information

Windows 10 Pro
Java 17

### Example Application

https://github.com/hantsy/micronaut-sandbox/tree/master/mongodb-album-service

### Version

4.0.0

**Comment by radovanradic** [comment]
@hantsy If you provide codec registry when creating collection, like in `AlbumRepository` then there won't be this error. Changed `CustomerRepository.customersCollection()` looking like this (need to register package for codec):
```
private MongoCollection<Customer> customersCollection() {
        var providers = fromProviders(
                mongoConfiguration.getClientSettings().build().getCodecRegistry(),
                PojoCodecProvider.builder()
                        .register("com.example.customers")
                        .conventions(Conventions.DEFAULT_CONVENTIONS)
                        .build());
        var codecRegistry = fromRegistries(List.of(providers));
        return mongoClient
                .getDatabase("userdb")
                .getCollection("customers", Customer.class)
                .withCodecRegistry(codecRegistry);
    }
```

**Comment by hantsy** [comment]
The MongoClient bean should include default configuration and default codecs for the general purpose. 

In the `albums` collections I just want to customize there.

The sample codes is working in Microaunt 3.x when I wrote them.

**Comment by radovanradic** [comment]
I tried the test with 3.9.4 and getting the same error.

**Comment by sh1bz** [comment]
I have the same exact issue.

**Comment by key-del-jeeinho** [comment]
I had the same error in Kotlin, and it was resolved by changing the document class to data class.

Would it be helpful to check if there are any annotations missing in Java's lombok?

**Comment by fromlabs** [comment]
I've put my `model` package in `test/resources/application-test.yml`:
```
mongodb:
  package-names: org.fromlabs.moody.importer.application.model
```
