### ISSUE TITLE
DataAccessException when loading only a complex field

### ISSUE THREAD

**Issue by Berlizov** [micronaut-projects/micronaut-mongodb#640]
### Expected Behavior

Entity:
```java
@MappedEntity
public class Entity {
    @Id
    @GeneratedValue
    private String id;
    private final String simpleValue;
    private final ComplexValue complexValue;

    @Serdeable
    public static class ComplexValue {
        private final String valueA;
        private final String valueB;
...
```
Repository:
```java
@MongoRepository
public interface EntityRepository extends CrudRepository<Entity, String> {
    Optional<String> findSimpleValueById(String id);
    Optional<Entity.ComplexValue> findComplexValueById(String id);
}
```

`Optional<Entity.ComplexValue> findComplexValueById(String id);` should return a valid object.

### Actual Behaviour

```
io.micronaut.data.exceptions.DataAccessException: Error instantiating type [com.example.Entity$ComplexValue] from introspection: Null argument specified for [valueA]. If this argument is allowed to be null annotate it with @Nullable
        at io.micronaut.data.runtime.mapper.BeanIntrospectionMapper.map(BeanIntrospectionMapper.java:110)
        at io.micronaut.data.mongodb.operations.AbstractMongoRepositoryOperations.convertResult(AbstractMongoRepositoryOperations.java:181)
        at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.findOneAggregated(DefaultMongoRepositoryOperations.java:304)
        at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.lambda$findOne$1(DefaultMongoRepositoryOperations.java:178)
        at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.lambda$withClientSession$19(DefaultMongoRepositoryOperations.java:749)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.withExistingConnectionInternal(AbstractConnectionOperations.java:128)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:92)
        at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.withClientSession(DefaultMongoRepositoryOperations.java:749)
        at io.micronaut.data.mongodb.operations.DefaultMongoRepositoryOperations.findOne(DefaultMongoRepositoryOperations.java:172)
        at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:47)
        at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:34)
        at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:83)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
        at com.example.EntityRepository$Intercepted.findComplexValueById(Unknown Source)
        at com.example.EntityRepositoryTest.should_load_complex_value_by_id(EntityRepositoryTest.java:42)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.micronaut.test.extensions.junit5.MicronautJunit5Extension$2.proceed(MicronautJunit5Extension.java:142)
        at io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:162)
        at io.micronaut.test.extensions.AbstractMicronautExtension$3.proceed(AbstractMicronautExtension.java:174)
        at io.micronaut.test.context.TestMethodInterceptor.interceptTest(TestMethodInterceptor.java:46)
        at io.micronaut.transaction.test.DefaultTestTransactionExecutionListener.lambda$interceptTest$0(DefaultTestTransactionExecutionListener.java:93)
        at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.lambda$execute$2(AbstractPropagatedStatusTransactionOperations.java:68)
        at io.micronaut.transaction.TransactionCallback.apply(TransactionCallback.java:37)
        at io.micronaut.transaction.support.AbstractTransactionOperations.executeTransactional(AbstractTransactionOperations.java:333)
        at io.micronaut.transaction.support.AbstractTransactionOperations.executeWithNewTransaction(AbstractTransactionOperations.java:318)
        at io.micronaut.transaction.support.AbstractTransactionOperations.executeNew(AbstractTransactionOperations.java:235)
        at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:137)
        at io.micronaut.transaction.support.AbstractTransactionOperations.lambda$doExecute$0(AbstractTransactionOperations.java:122)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.executeWithNewConnection(AbstractConnectionOperations.java:143)
        at io.micronaut.data.connection.support.AbstractConnectionOperations.execute(AbstractConnectionOperations.java:90)
        at io.micronaut.transaction.support.AbstractTransactionOperations.doExecute(AbstractTransactionOperations.java:120)
        at io.micronaut.transaction.support.AbstractPropagatedStatusTransactionOperations.execute(AbstractPropagatedStatusTransactionOperations.java:65)
        at io.micronaut.transaction.test.DefaultTestTransactionExecutionListener.interceptTest(DefaultTestTransactionExecutionListener.java:91)
        at io.micronaut.test.extensions.AbstractMicronautExtension.interceptEach(AbstractMicronautExtension.java:166)
        at io.micronaut.test.extensions.AbstractMicronautExtension.interceptTest(AbstractMicronautExtension.java:119)
        at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.interceptTestMethod(MicronautJunit5Extension.java:129)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.micronaut.core.reflect.exception.InstantiationException: Null argument specified for [valueA]. If this argument is allowed to be null annotate it with @Nullable
        at io.micronaut.inject.beans.AbstractInitializableBeanIntrospection.instantiate(AbstractInitializableBeanIntrospection.java:350)
        at io.micronaut.core.beans.BeanIntrospection.instantiate(BeanIntrospection.java:130)
        at io.micronaut.data.runtime.mapper.BeanIntrospectionMapper.map(BeanIntrospectionMapper.java:80)
        ... 37 more
```

AbstractMongoRepositoryOperations:169
The loaded document is:
```json
{"_id": {"$oid": "66320ff0fdb12a260ebadac3"}, "complexValue": {"valueA": "valueA", "valueB": "valueB"}}
```
But alias is `valueA`, not `complexValue.valueA` or something like this. So, it cannot find this alias in the document.

<img width="598" alt="Снимок экрана 2024-05-01 в 12 45 56" src="https://github.com/micronaut-projects/micronaut-mongodb/assets/5638172/7f5af148-7abe-4f3d-b7ec-aed9fdd8b163">

### Steps To Reproduce

1. https://github.com/Berlizov/micronaut-mongodb-bug
2. Run EntityRepositoryTest.should_load_complex_value_by_id()
3. See error

### Example Application

https://github.com/Berlizov/micronaut-mongodb-bug

### Version

4.4.1

**Comment by Berlizov** [comment]
sorry, wrong repo
